name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          

      

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t djangokubernetesproject:${{ github.sha }} .
          docker tag djangokubernetesproject:${{ github.sha }} santoshkr567/djangokubernetesproject:${{ github.sha }}
          docker push santoshkr567/djangokubernetesproject:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
          REGISTRY: docker.io
          DOCKER_USERNAME: santoshkr567
          DOCKER_PASSWORD: setting123

      # Optional: Update Kubernetes manifests (if necessary)
      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|djangokubernetesproject:latest|djangokubernetesproject:${{ github.sha }}|" k8s/deployment.yaml
          git add k8s/deployment.yaml
          git commit -m "Update deployment with new image version"
          git push
