name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t djangokubernetesproject:${{ github.sha }} .
          docker tag djangokubernetesproject:${{ github.sha }} santoshkr567/djangokubernetesproject:${{ github.sha }}
          
      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "setting123" | docker login --username "santoshkr567" --password-stdin

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push santoshkr567/djangokubernetesproject:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
          REGISTRY: docker.io

      - name: Update Kustomize overlay with new image tag
        run: |
          sed -i "s/latest/${{ github.sha }}/" k8s/overlays/prod/kustomization.yaml
          
      - name: Apply Kubernetes manifests with Kustomize
        run: |
          kubectl apply -k overlays/prod
