name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t djangokubernetesproject:${{ github.sha }} .
          docker tag djangokubernetesproject:${{ github.sha }} santoshkr567/djangokubernetesproject:${{ github.sha }}
          
      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "setting123" | docker login --username "santoshkr567" --password-stdin

      # Push Docker image
      - name: Push Docker image
        run: |
          docker push santoshkr567/djangokubernetesproject:${{ github.sha }}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_EXPERIMENTAL: enabled
          REGISTRY: docker.io

      # Optional: Update Kubernetes Manifests
      - name: Update Kubernetes Manifests
        run: |
          sed -i "s|djangokubernetesproject:latest|djangokubernetesproject:${{ github.sha }}|" k8s/django-deployment.yaml

          git config --local user.email "santoshkrm567@gmail.com"  
          git config --local user.name "santoshkr567" 

          git add k8s/django-deployment.yml
          git commit -m "Update deployment with new image version"
          git push https://x-access-token:${{ secrets.PAT }}@github.com/$santoshkr567/djangokubernetesproject.git
